// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.chariotsolutions.rabbitmq.domain;

privileged aspect Mezzage_Roo_JavaBean {
    
    public java.lang.String Mezzage.getMessageBody() {
        return this.messageBody;
    }
    
    public void Mezzage.setMessageBody(java.lang.String messageBody) {
        this.messageBody = messageBody;
    }
    
}
